$(document).ready(function(){
  $("#ba0").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba15").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba16").css("top",'500px',function(){
    $("#ba0").css("top","500px");
    });
  });
  $("#ba1").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba16").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba0").css("top",'500px',function(){
    $("#ba1").css("top","500px");
    });
  });
  $("#ba2").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba0").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba1").css("top",'500px',function(){
    $("#ba2").css("top","500px");
    });
  });
  $("#ba3").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba1").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba2").css("top",'500px',function(){
    $("#ba3").css("top","500px");
    });
  });
  $("#ba4").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba2").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba3").css("top",'500px',function(){
    $("#ba4").css("top","500px");
    });
  });
  $("#ba5").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba3").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba4").css("top",'500px',function(){
    $("#ba5").css("top","500px");
    });
  });
  $("#ba6").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba4").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba5").css("top",'500px',function(){
    $("#ba6").css("top","500px");
    });
  });
  $("#ba7").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba5").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba6").css("top",'500px',function(){
    $("#ba7").css("top","500px");
    });
  });
  $("#ba8").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba6").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba7").css("top",'500px',function(){
    $("#ba8").css("top","500px");
    });
  });
  $("#ba9").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba7").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba8").css("top",'500px',function(){
    $("#ba9").css("top","500px");
    });
  });
  $("#ba10").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba8").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba9").css("top",'500px',function(){
    $("#ba10").css("top","500px");
    });
  });
  $("#ba11").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba9").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba10").css("top",'500px',function(){
    $("#ba11").css("top","500px");
    });
  });
  $("#ba12").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba10").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba11").css("top",'500px',function(){
    $("#ba12").css("top","500px");
    });
  });
  $("#ba13").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba11").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba12").css("top",'500px',function(){
    $("#ba13").css("top","500px");
    });
  });
  $("#ba14").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba12").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba13").css("top",'500px',function(){
    $("#ba14").css("top","500px");
    });
  });
  $("#ba15").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba13").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba14").css("top",'500px',function(){
    $("#ba15").css("top","500px");
    });
  });
  $("#ba16").click(function(){
    $(this).animate({top:'-500px'}),
    $("#ba14").css({"display":"block","top":"500px"}).animate({top:'0'}),
    $("#ba15").css("top",'500px',function(){
    $("#ba16").css("top","500px");
    });
  });
});